language: node_js
node_js:
  - 4.3.1
script:
  - npm test
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: hT0Ba43+HgHbDpmeG9BBoE1A8UZwXpttZ0PSGOVIxcXZ4fWzMTgmfQXlVG3WlrwTeyLzuCQYBTIQ0UT1Ub6yTChKcXrkcq4pecSdD/8oJnCBtohSTFt8TQP7duWZM41wjDv+NfSMT+zP648KxVyadU9vxxALyCOQJNdkhZej90wYxvQtZf6b8PdYMVEbpBahkh2lTloMgYEC865i3zwwUqfyT0C0SJZdlbDH+IQ0Zk31sPut8LoPwsrq4neRF3oJeDOTcaGk6S03PLWhi2oUiMuP8sbYy6yKTNIhvRaUFhre+JQNYY5KsihK/Z2/yJtrUSF9aiGf8UUMnPd99tlTRSv9ojySpkNi4aEnOWNTrdD4Ro0Qq/VD1ZIfhjd9oJDkSNnyib65XuPn3ASfaFsqr36X4YUjHFelqKQeLXyR8faYuxFPKZ8o3/N1PAEFo6IXFLRSqhSKzhLsJ2SXmaeGzaDIDn9RdbwS+/dHJAzQTG74wh9SQKHgqXxKduR3uazDPJ6b9eiz4pM9N1Wdsqvf1j6fo1/WK/zrQoAvQpkSy4P5MgBrmSWYDCDpzBRqiBmP6NKTJuacpqgWPKWNJLzsyE7Cw1t64mk4aFAnVyerxNPfq/TnNSh2aklzYXXSAE3JNuHYHA0FPxcBu25wykT9SZwv2ppMflhWb4eUyJb/BHM=
